-- Migration: Catálogo de legendas de exames (bilateral support)
CREATE TABLE IF NOT EXISTS `exam_legends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exam_name` VARCHAR(255) NOT NULL,
  `modality` VARCHAR(20) NOT NULL DEFAULT 'outros',
  `bilateral` BOOLEAN NOT NULL DEFAULT FALSE,
  `sort_order` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_exam_name` (`exam_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed: exames bilaterais por modalidade
INSERT IGNORE INTO `exam_legends` (`exam_name`, `modality`, `bilateral`, `sort_order`) VALUES
-- Radiografia (RX)
('Radiografia de Ombro', 'rx', TRUE, 10),
('Radiografia de Joelho', 'rx', TRUE, 20),
('Radiografia de Tornozelo', 'rx', TRUE, 30),
('Radiografia de Pé', 'rx', TRUE, 40),
('Radiografia de Mão', 'rx', TRUE, 50),
('Radiografia de Punho', 'rx', TRUE, 60),
('Radiografia de Cotovelo', 'rx', TRUE, 70),
('Radiografia de Quadril', 'rx', TRUE, 80),
('Radiografia de Tórax PA e Perfil', 'rx', FALSE, 90),
('Radiografia de Tórax PA', 'rx', FALSE, 100),
('Radiografia de Seios da Face', 'rx', FALSE, 110),
('Radiografia de Coluna Cervical AP e Perfil', 'rx', FALSE, 120),
('Radiografia de Coluna Lombar AP e Perfil', 'rx', FALSE, 130),
('Radiografia de Abdome sem Preparo', 'rx', FALSE, 140),
('Radiografia de Bacia AP', 'rx', FALSE, 150),
('Radiografia de Crânio AP e Perfil', 'rx', FALSE, 160),
('Mamografia Bilateral', 'rx', FALSE, 170),
-- Tomografia (TC)
('Tomografia Computadorizada de Ombro', 'tc', TRUE, 10),
('Tomografia Computadorizada de Joelho', 'tc', TRUE, 20),
('Tomografia Computadorizada de Quadril', 'tc', TRUE, 30),
('Tomografia Computadorizada de Órbitas', 'tc', TRUE, 40),
('Tomografia Computadorizada de Mastoides', 'tc', TRUE, 50),
('Tomografia Computadorizada de Crânio sem Contraste', 'tc', FALSE, 60),
('Tomografia Computadorizada de Crânio com Contraste', 'tc', FALSE, 70),
('Tomografia Computadorizada de Tórax sem Contraste', 'tc', FALSE, 80),
('Tomografia Computadorizada de Tórax com Contraste', 'tc', FALSE, 90),
('Tomografia Computadorizada de Abdome e Pelve sem Contraste', 'tc', FALSE, 100),
('Tomografia Computadorizada de Abdome e Pelve com Contraste', 'tc', FALSE, 110),
('Tomografia Computadorizada de Coluna Cervical', 'tc', FALSE, 120),
('Tomografia Computadorizada de Coluna Lombar', 'tc', FALSE, 130),
('Tomografia Computadorizada de Seios da Face', 'tc', FALSE, 140),
('Tomografia Computadorizada de Pescoço', 'tc', FALSE, 150),
('Tomografia Computadorizada de Pelve', 'tc', FALSE, 160),
('Angiotomografia de Coronárias', 'tc', FALSE, 170),
('Angiotomografia de Aorta', 'tc', FALSE, 180),
('Angiotomografia Cerebral', 'tc', FALSE, 190),
-- Ultrassom (US)
('Ultrassonografia de Mama', 'us', TRUE, 10),
('Ultrassonografia de Ombro', 'us', TRUE, 20),
('Ultrassonografia de Joelho', 'us', TRUE, 30),
('Ultrassonografia de Testículo', 'us', TRUE, 40),
('Ultrassonografia Doppler de Membros Inferiores', 'us', TRUE, 50),
('Ultrassonografia Doppler de Membros Superiores', 'us', TRUE, 60),
('Ultrassonografia de Abdome Total', 'us', FALSE, 70),
('Ultrassonografia de Abdome Superior', 'us', FALSE, 80),
('Ultrassonografia Pélvica Transvaginal', 'us', FALSE, 90),
('Ultrassonografia Pélvica Suprapúbica', 'us', FALSE, 100),
('Ultrassonografia de Tireoide', 'us', FALSE, 110),
('Ultrassonografia de Partes Moles', 'us', FALSE, 120),
('Ultrassonografia Doppler de Carótidas', 'us', FALSE, 130),
('Ultrassonografia de Próstata', 'us', FALSE, 140),
('Ultrassonografia Obstétrica', 'us', FALSE, 150),
('Ultrassonografia Morfológica', 'us', FALSE, 160),
-- Ressonância (RM)
('Ressonância Magnética de Joelho', 'rm', TRUE, 10),
('Ressonância Magnética de Ombro', 'rm', TRUE, 20),
('Ressonância Magnética de Quadril', 'rm', TRUE, 30),
('Ressonância Magnética de Tornozelo', 'rm', TRUE, 40),
('Ressonância Magnética de Punho', 'rm', TRUE, 50),
('Ressonância Magnética de Cotovelo', 'rm', TRUE, 60),
('Ressonância Magnética de Crânio sem Contraste', 'rm', FALSE, 70),
('Ressonância Magnética de Crânio com Contraste', 'rm', FALSE, 80),
('Ressonância Magnética de Coluna Cervical', 'rm', FALSE, 90),
('Ressonância Magnética de Coluna Torácica', 'rm', FALSE, 100),
('Ressonância Magnética de Coluna Lombar', 'rm', FALSE, 110),
('Ressonância Magnética de Abdome', 'rm', FALSE, 120),
('Ressonância Magnética de Pelve', 'rm', FALSE, 130),
('Angiorressonância Cerebral', 'rm', FALSE, 140),
('Angiorressonância de Carótidas', 'rm', FALSE, 150);
