-- Migration 0033: Adicionar CREATE_LAYOUT, UPDATE_LAYOUT, DELETE_LAYOUT ao enum audit_log.action

ALTER TABLE `audit_log`
MODIFY COLUMN `action` ENUM(
  'LOGIN','LOGOUT','VIEW_STUDY','OPEN_VIEWER',
  'CREATE_REPORT','UPDATE_REPORT','SIGN_REPORT','DELETE_REPORT','REVISE_REPORT',
  'CREATE_USER','UPDATE_USER','DELETE_USER','ACTIVATE_USER','DEACTIVATE_USER',
  'CREATE_UNIT','UPDATE_UNIT','DELETE_UNIT',
  'PACS_QUERY','PACS_DOWNLOAD',
  'CREATE_ANAMNESIS','EDIT_STUDY_METADATA',
  'RESET_DOCTOR_BILLING',
  'CREATE_LAYOUT','UPDATE_LAYOUT','DELETE_LAYOUT'
) NOT NULL;
