-- Migration 0061: Adicionar GRANT_FINANCIAL_RESPONSIBLE_ACCESS e
-- REVOKE_FINANCIAL_RESPONSIBLE_ACCESS ao enum audit_log.action.
--
-- Usados pelas mutations financeSimple.linkUser / financeSimple.unlinkUser
-- (gestão de usuários de acesso de um responsável financeiro), que antes desta
-- migration não geravam nenhum registro de auditoria — item 6 do documento de
-- requisitos REQUISITOS_FUNCIONALIDADE_RESPONSAVEL_FINANCEIRO_2026-09-17 exige
-- que toda operação administrativa desse tipo seja auditável.

ALTER TABLE `audit_log`
MODIFY COLUMN `action` ENUM(
  'LOGIN','LOGOUT','VIEW_STUDY','OPEN_VIEWER','CREATE_REPORT','UPDATE_REPORT','SIGN_REPORT',
  'DELETE_REPORT','CANCEL_REPORT','REVISE_REPORT','CREATE_USER','UPDATE_USER','DELETE_USER',
  'ACTIVATE_USER','DEACTIVATE_USER','CREATE_UNIT','UPDATE_UNIT','DELETE_UNIT','PACS_QUERY',
  'PACS_DOWNLOAD','CREATE_ANAMNESIS','EDIT_STUDY_METADATA','SET_STUDY_PRIORITY',
  'UPDATE_STUDY_PRIORITY','CLEAR_STUDY_PRIORITY','RESET_DOCTOR_BILLING','CREATE_LAYOUT',
  'UPDATE_LAYOUT','DELETE_LAYOUT','BILLING_EVENT_FAILED','FINANCIAL_ENABLED','FINANCIAL_DISABLED',
  'BILLING_EVENT_WITHOUT_FINANCIAL_ENABLED','BILLING_EVENT_CANCELLED',
  'DOCTOR_PAYMENT_CONFIRMED','DOCTOR_PAYMENT_DISPUTED','SET_EXTERNAL_SALE_PRICE',
  'GRANT_FINANCIAL_RESPONSIBLE_ACCESS','REVOKE_FINANCIAL_RESPONSIBLE_ACCESS'
) NOT NULL;
