-- Seed: exam_catalog
-- Gerado automaticamente por seed-exam-catalog.py
-- Total: 370 exames

INSERT INTO exam_catalog (modality, title, keywords, active) VALUES
  ('CR', 'sem contraste', 'sem contraste', 1),
  ('CR', 'com contraste', 'com contraste', 1),
  ('CR', 'pré e pós-contraste', 'pré e pós-contraste', 1),
  ('CR', 'com sedação', 'com sedação', 1),
  ('CR', 'bilateral / unilateral', 'bilateral / unilateral', 1),
  ('CR', 'com manobras / incidências especiais', 'com manobras / incidências especiais', 1),
  ('CR', 'modalidade', 'modalidade', 1),
  ('CR', 'região anatômica', 'região anatômica', 1),
  ('CR', 'incidência / protocolo', 'incidência / protocolo', 1),
  ('CR', 'lateralidade', 'lateralidade', 1),
  ('CR', 'observação operacional', 'observação operacional', 1),
  ('CR', 'Radiografia de Tórax PA', 'tórax pa', 1),
  ('CR', 'Radiografia de Tórax AP', 'tórax ap', 1),
  ('CR', 'Radiografia de Tórax Perfil', 'tórax perfil', 1),
  ('CR', 'Radiografia de Tórax PA e Perfil', 'tórax pa e perfil', 1),
  ('CR', 'Radiografia de Tórax AP e Perfil', 'tórax ap e perfil', 1),
  ('CR', 'Radiografia de Tórax AP e Oblíquas', 'tórax ap e oblíquas', 1),
  ('CR', 'Radiografia de Tórax PA e Oblíquas', 'tórax pa e oblíquas', 1),
  ('CR', 'Radiografia de Tórax em Decúbito', 'tórax em decúbito', 1),
  ('CR', 'Radiografia de Tórax em Expiração', 'tórax em expiração', 1),
  ('CR', 'Radiografia de Tórax Inspirado e Expirado', 'tórax inspirado e expirado', 1),
  ('CR', 'Radiografia de Tórax Trauma', 'tórax trauma', 1),
  ('CR', 'Radiografia de Tórax Portátil AP', 'tórax portátil ap', 1),
  ('CR', 'Radiografia de Arcos Costais Bilateral', 'arcos costais bilateral', 1),
  ('CR', 'Radiografia de Arcos Costais Direita', 'arcos costais direita', 1),
  ('CR', 'Radiografia de Arcos Costais Esquerda', 'arcos costais esquerda', 1),
  ('CR', 'Radiografia de Esterno', 'esterno', 1),
  ('CR', 'Radiografia de Esterno Perfil', 'esterno perfil', 1),
  ('CR', 'Radiografia de Esterno Oblíquas', 'esterno oblíquas', 1),
  ('CR', 'Radiografia de Articulações Esternoclaviculares', 'articulações esternoclaviculares', 1),
  ('CR', 'Radiografia de Seios da Face Fronto-Naso', 'seios da face fronto-naso', 1),
  ('CR', 'Radiografia de Seios da Face Mento-Naso', 'seios da face mento-naso', 1),
  ('CR', 'Radiografia de Seios da Face Perfil', 'seios da face perfil', 1),
  ('CR', 'Radiografia de Seios da Face Fronto-Naso, Mento-Naso e Perfil', 'seios da face fronto-naso, mento-naso e perfil', 1),
  ('CR', 'Radiografia de Face', 'face', 1),
  ('CR', 'Radiografia de Ossos Nasais', 'ossos nasais', 1),
  ('CR', 'Radiografia de Ossos Nasais Perfil', 'ossos nasais perfil', 1),
  ('CR', 'Radiografia de Ossos Nasais Fronto-Naso', 'ossos nasais fronto-naso', 1),
  ('CR', 'Radiografia de Zigomáticos', 'zigomáticos', 1),
  ('CR', 'Radiografia de Arcos Zigomáticos', 'arcos zigomáticos', 1),
  ('CR', 'Radiografia de Órbitas', 'órbitas', 1),
  ('CR', 'Radiografia de Mandíbula PA', 'mandíbula pa', 1),
  ('CR', 'Radiografia de Mandíbula Perfil', 'mandíbula perfil', 1),
  ('CR', 'Radiografia de Mandíbula Oblíquas', 'mandíbula oblíquas', 1),
  ('CR', 'Radiografia de Articulação Temporomandibular Bilateral', 'articulação temporomandibular bilateral', 1),
  ('CR', 'Radiografia de ATM Bilateral Boca Aberta e Fechada', 'atm bilateral boca aberta e fechada', 1),
  ('CR', 'Radiografia de Cavum', 'cavum', 1),
  ('CR', 'Radiografia de Crânio PA', 'crânio pa', 1),
  ('CR', 'Radiografia de Crânio AP', 'crânio ap', 1),
  ('CR', 'Radiografia de Crânio Perfil', 'crânio perfil', 1),
  ('CR', 'Radiografia de Crânio PA e Perfil', 'crânio pa e perfil', 1),
  ('CR', 'Radiografia de Crânio AP, Perfil e Towne', 'crânio ap, perfil e towne', 1),
  ('CR', 'Radiografia de Sela Túrcica', 'sela túrcica', 1),
  ('CR', 'Radiografia de Mastoides', 'mastoides', 1),
  ('CR', 'Radiografia de Forames Ópticos', 'forames ópticos', 1),
  ('CR', 'Radiografia de Coluna Cervical AP', 'coluna cervical ap', 1),
  ('CR', 'Radiografia de Coluna Cervical Perfil', 'coluna cervical perfil', 1),
  ('CR', 'Radiografia de Coluna Cervical AP e Perfil', 'coluna cervical ap e perfil', 1),
  ('CR', 'Radiografia de Coluna Cervical AP, Perfil e Oblíquas', 'coluna cervical ap, perfil e oblíquas', 1),
  ('CR', 'Radiografia de Coluna Cervical com Boca Aberta', 'coluna cervical com boca aberta', 1),
  ('CR', 'Radiografia de Coluna Cervical Dinâmica', 'coluna cervical dinâmica', 1),
  ('CR', 'Radiografia de Coluna Cervical em Flexão', 'coluna cervical em flexão', 1),
  ('CR', 'Radiografia de Coluna Cervical em Extensão', 'coluna cervical em extensão', 1),
  ('CR', 'Radiografia de Coluna Cérvico-Torácica', 'coluna cérvico-torácica', 1),
  ('CR', 'Radiografia de Coluna Torácica AP', 'coluna torácica ap', 1),
  ('CR', 'Radiografia de Coluna Torácica Perfil', 'coluna torácica perfil', 1),
  ('CR', 'Radiografia de Coluna Torácica AP e Perfil', 'coluna torácica ap e perfil', 1),
  ('CR', 'Radiografia de Coluna Lombar AP', 'coluna lombar ap', 1),
  ('CR', 'Radiografia de Coluna Lombar Perfil', 'coluna lombar perfil', 1),
  ('CR', 'Radiografia de Coluna Lombar AP e Perfil', 'coluna lombar ap e perfil', 1),
  ('CR', 'Radiografia de Coluna Lombar AP, Perfil e Oblíquas', 'coluna lombar ap, perfil e oblíquas', 1),
  ('CR', 'Radiografia de Coluna Lombossacra', 'coluna lombossacra', 1),
  ('CR', 'Radiografia de Coluna Lombossacra AP e Perfil', 'coluna lombossacra ap e perfil', 1),
  ('CR', 'Radiografia de Coluna Lombar Dinâmica', 'coluna lombar dinâmica', 1),
  ('CR', 'Radiografia de Coluna Lombar em Flexão', 'coluna lombar em flexão', 1),
  ('CR', 'Radiografia de Coluna Lombar em Extensão', 'coluna lombar em extensão', 1),
  ('CR', 'Radiografia de Sacro e Cóccix AP e Perfil', 'sacro e cóccix ap e perfil', 1),
  ('CR', 'Radiografia de Sacroilíacas', 'sacroilíacas', 1),
  ('CR', 'Radiografia de Bacia AP', 'bacia ap', 1),
  ('CR', 'Radiografia de Bacia AP e Frog', 'bacia ap e frog', 1),
  ('CR', 'Radiografia de Pelve', 'pelve', 1),
  ('CR', 'Radiografia de Pelvimetria', 'pelvimetria', 1),
  ('CR', 'Radiografia de Abdome AP', 'abdome ap', 1),
  ('CR', 'Radiografia de Abdome em Ortostase', 'abdome em ortostase', 1),
  ('CR', 'Radiografia de Abdome em Decúbito', 'abdome em decúbito', 1),
  ('CR', 'Radiografia de Abdome Agudo', 'abdome agudo', 1),
  ('CR', 'Radiografia de Abdome Agudo Série', 'abdome agudo série', 1),
  ('CR', 'Radiografia de Abdome Total', 'abdome total', 1),
  ('CR', 'Radiografia de Clavícula Direita', 'clavícula direita', 1),
  ('CR', 'Radiografia de Clavícula Esquerda', 'clavícula esquerda', 1),
  ('CR', 'Radiografia de Clavículas Bilateral', 'clavículas bilateral', 1),
  ('CR', 'Radiografia de Escápula Direita', 'escápula direita', 1),
  ('CR', 'Radiografia de Escápula Esquerda', 'escápula esquerda', 1),
  ('CR', 'Radiografia de Ombro Direito AP', 'ombro direito ap', 1),
  ('CR', 'Radiografia de Ombro Esquerdo AP', 'ombro esquerdo ap', 1),
  ('CR', 'Radiografia de Ombro Direito AP e Perfil', 'ombro direito ap e perfil', 1),
  ('CR', 'Radiografia de Ombro Esquerdo AP e Perfil', 'ombro esquerdo ap e perfil', 1),
  ('CR', 'Radiografia de Ombro Direito com Rotação Interna e Externa', 'ombro direito com rotação interna e externa', 1),
  ('CR', 'Radiografia de Ombro Esquerdo com Rotação Interna e Externa', 'ombro esquerdo com rotação interna e externa', 1),
  ('CR', 'Radiografia de Ombro Bilateral', 'ombro bilateral', 1),
  ('CR', 'Radiografia de Acrômio-Clavicular', 'acrômio-clavicular', 1),
  ('CR', 'Radiografia de Acrômio-Clavicular com e sem Peso', 'acrômio-clavicular com e sem peso', 1),
  ('CR', 'Radiografia de Articulações Acromioclaviculares Bilateral', 'articulações acromioclaviculares bilateral', 1),
  ('CR', 'Radiografia de Úmero Direito', 'úmero direito', 1),
  ('CR', 'Radiografia de Úmero Esquerdo', 'úmero esquerdo', 1),
  ('CR', 'Radiografia de Cotovelo Direito AP e Perfil', 'cotovelo direito ap e perfil', 1),
  ('CR', 'Radiografia de Cotovelo Esquerdo AP e Perfil', 'cotovelo esquerdo ap e perfil', 1),
  ('CR', 'Radiografia de Cotovelo Direito com Oblíquas', 'cotovelo direito com oblíquas', 1),
  ('CR', 'Radiografia de Cotovelo Esquerdo com Oblíquas', 'cotovelo esquerdo com oblíquas', 1),
  ('CR', 'Radiografia de Antebraço Direito', 'antebraço direito', 1),
  ('CR', 'Radiografia de Antebraço Esquerdo', 'antebraço esquerdo', 1),
  ('CR', 'Radiografia de Punho Direito PA e Perfil', 'punho direito pa e perfil', 1),
  ('CR', 'Radiografia de Punho Esquerdo PA e Perfil', 'punho esquerdo pa e perfil', 1),
  ('CR', 'Radiografia de Punho Direito com Oblíquas', 'punho direito com oblíquas', 1),
  ('CR', 'Radiografia de Punho Esquerdo com Oblíquas', 'punho esquerdo com oblíquas', 1),
  ('CR', 'Radiografia de Punho Direito para Escafóide', 'punho direito para escafóide', 1),
  ('CR', 'Radiografia de Punho Esquerdo para Escafóide', 'punho esquerdo para escafóide', 1),
  ('CR', 'Radiografia de Mão Direita PA, Oblíqua e Perfil', 'mão direita pa, oblíqua e perfil', 1),
  ('CR', 'Radiografia de Mão Esquerda PA, Oblíqua e Perfil', 'mão esquerda pa, oblíqua e perfil', 1),
  ('CR', 'Radiografia de Quirodáctilos da Mão Direita', 'quirodáctilos da mão direita', 1),
  ('CR', 'Radiografia de Quirodáctilos da Mão Esquerda', 'quirodáctilos da mão esquerda', 1),
  ('CR', 'Radiografia de Dedo Direito', 'dedo direito', 1),
  ('CR', 'Radiografia de Dedo Esquerdo', 'dedo esquerdo', 1),
  ('CR', 'Radiografia de Polegar Direito', 'polegar direito', 1),
  ('CR', 'Radiografia de Polegar Esquerdo', 'polegar esquerdo', 1),
  ('CR', 'Radiografia para Idade Óssea', 'radiografia para idade óssea', 1),
  ('CR', 'Radiografia de Quadril Direito AP e Perfil', 'quadril direito ap e perfil', 1),
  ('CR', 'Radiografia de Quadril Esquerdo AP e Perfil', 'quadril esquerdo ap e perfil', 1),
  ('CR', 'Radiografia de Quadris Bilateral', 'quadris bilateral', 1),
  ('CR', 'Radiografia de Fêmur Direito', 'fêmur direito', 1),
  ('CR', 'Radiografia de Fêmur Esquerdo', 'fêmur esquerdo', 1),
  ('CR', 'Radiografia de Joelho Direito AP e Perfil', 'joelho direito ap e perfil', 1),
  ('CR', 'Radiografia de Joelho Esquerdo AP e Perfil', 'joelho esquerdo ap e perfil', 1),
  ('CR', 'Radiografia de Joelho Direito AP, Perfil e Axial de Patela', 'joelho direito ap, perfil e axial de patela', 1),
  ('CR', 'Radiografia de Joelho Esquerdo AP, Perfil e Axial de Patela', 'joelho esquerdo ap, perfil e axial de patela', 1),
  ('CR', 'Radiografia de Joelho Bilateral', 'joelho bilateral', 1),
  ('CR', 'Radiografia de Patela Direita Axial', 'patela direita axial', 1),
  ('CR', 'Radiografia de Patela Esquerda Axial', 'patela esquerda axial', 1),
  ('CR', 'Radiografia de Perna Direita', 'perna direita', 1),
  ('CR', 'Radiografia de Perna Esquerda', 'perna esquerda', 1),
  ('CR', 'Radiografia de Tornozelo Direito AP, Perfil e Oblíquas', 'tornozelo direito ap, perfil e oblíquas', 1),
  ('CR', 'Radiografia de Tornozelo Esquerdo AP, Perfil e Oblíquas', 'tornozelo esquerdo ap, perfil e oblíquas', 1),
  ('CR', 'Radiografia de Pé Direito AP, Perfil e Oblíquas', 'pé direito ap, perfil e oblíquas', 1),
  ('CR', 'Radiografia de Pé Esquerdo AP, Perfil e Oblíquas', 'pé esquerdo ap, perfil e oblíquas', 1),
  ('CR', 'Radiografia de Calcâneo Direito Axial e Perfil', 'calcâneo direito axial e perfil', 1),
  ('CR', 'Radiografia de Calcâneo Esquerdo Axial e Perfil', 'calcâneo esquerdo axial e perfil', 1),
  ('CR', 'Radiografia de Pododáctilos do Pé Direito', 'pododáctilos do pé direito', 1),
  ('CR', 'Radiografia de Pododáctilos do Pé Esquerdo', 'pododáctilos do pé esquerdo', 1),
  ('CR', 'Radiografia de Hálux Direito', 'hálux direito', 1),
  ('CR', 'Radiografia de Hálux Esquerdo', 'hálux esquerdo', 1),
  ('CR', 'Escanometria de Membros Inferiores', 'escanometria de membros inferiores', 1),
  ('CR', 'Escanometria Panorâmica de Membros Inferiores', 'escanometria panorâmica de membros inferiores', 1),
  ('CR', 'Radiografia Panorâmica de Membros Inferiores', 'radiografia panorâmica de membros inferiores', 1),
  ('CR', 'Radiografia Panorâmica de Coluna', 'radiografia panorâmica de coluna', 1),
  ('CT', 'Tomografia Computadorizada de Crânio sem Contraste', 'crânio sem contraste', 1),
  ('CT', 'Tomografia Computadorizada de Crânio com Contraste', 'crânio com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Crânio sem e com Contraste', 'crânio sem e com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Face', 'face', 1),
  ('CT', 'Tomografia Computadorizada de Órbitas', 'órbitas', 1),
  ('CT', 'Tomografia Computadorizada de Ossos Temporais', 'ossos temporais', 1),
  ('CT', 'Tomografia Computadorizada de Sela Túrcica', 'sela túrcica', 1),
  ('CT', 'Tomografia Computadorizada de Seios da Face', 'seios da face', 1),
  ('CT', 'Tomografia Computadorizada de Mandíbula', 'mandíbula', 1),
  ('CT', 'Tomografia Computadorizada de ATM', 'atm', 1),
  ('CT', 'Angiotomografia de Crânio', 'crânio', 1),
  ('CT', 'Angiotomografia de Carótidas', 'carótidas', 1),
  ('CT', 'Angiotomografia de Crânio e Pescoço', 'crânio e pescoço', 1),
  ('CT', 'Perfusão Cerebral por TC', 'perfusão cerebral por tc', 1),
  ('CT', 'Tomografia Computadorizada de Pescoço sem Contraste', 'pescoço sem contraste', 1),
  ('CT', 'Tomografia Computadorizada de Pescoço com Contraste', 'pescoço com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Pescoço sem e com Contraste', 'pescoço sem e com contraste', 1),
  ('CT', 'Angiotomografia de Vasos do Pescoço', 'vasos do pescoço', 1),
  ('CT', 'Tomografia Computadorizada de Tórax sem Contraste', 'tórax sem contraste', 1),
  ('CT', 'Tomografia Computadorizada de Tórax com Contraste', 'tórax com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Tórax sem e com Contraste', 'tórax sem e com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Alta Resolução do Tórax', 'alta resolução do tórax', 1),
  ('CT', 'Tomografia Computadorizada de Tórax para Trauma', 'tórax para trauma', 1),
  ('CT', 'Angiotomografia de Tórax', 'tórax', 1),
  ('CT', 'Angiotomografia de Artérias Pulmonares', 'artérias pulmonares', 1),
  ('CT', 'Angiotomografia de Aorta Torácica', 'aorta torácica', 1),
  ('CT', 'Tomografia Computadorizada de Esterno', 'esterno', 1),
  ('CT', 'Tomografia Computadorizada de Arcos Costais', 'arcos costais', 1),
  ('CT', 'Tomografia Computadorizada de Abdome Superior sem Contraste', 'abdome superior sem contraste', 1),
  ('CT', 'Tomografia Computadorizada de Abdome Superior com Contraste', 'abdome superior com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Abdome Total sem Contraste', 'abdome total sem contraste', 1),
  ('CT', 'Tomografia Computadorizada de Abdome Total com Contraste', 'abdome total com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Abdome Total sem e com Contraste', 'abdome total sem e com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Fígado', 'fígado', 1),
  ('CT', 'Tomografia Computadorizada de Pâncreas', 'pâncreas', 1),
  ('CT', 'Tomografia Computadorizada de Vias Biliares', 'vias biliares', 1),
  ('CT', 'Tomografia Computadorizada de Baço', 'baço', 1),
  ('CT', 'Tomografia Computadorizada de Rins e Vias Urinárias', 'rins e vias urinárias', 1),
  ('CT', 'Urotomografia', 'urotomografia', 1),
  ('CT', 'Angiotomografia de Aorta Abdominal', 'aorta abdominal', 1),
  ('CT', 'Angiotomografia de Artérias Renais', 'artérias renais', 1),
  ('CT', 'Colonografia por TC', 'colonografia por tc', 1),
  ('CT', 'Tomografia Computadorizada de Pelve sem Contraste', 'pelve sem contraste', 1),
  ('CT', 'Tomografia Computadorizada de Pelve com Contraste', 'pelve com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Pelve sem e com Contraste', 'pelve sem e com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Pelve Feminina', 'pelve feminina', 1),
  ('CT', 'Tomografia Computadorizada de Pelve Masculina', 'pelve masculina', 1),
  ('CT', 'Tomografia Computadorizada de Bacia', 'bacia', 1),
  ('CT', 'Angiotomografia de Pelve', 'pelve', 1),
  ('CT', 'Tomografia Computadorizada de Abdome total', 'abdome total', 1),
  ('CT', 'Tomografia Computadorizada de Abdome e Pelve com Contraste', 'abdome e pelve com contraste', 1),
  ('CT', 'Tomografia Computadorizada de Abdome e Pelve sem e com Contraste', 'abdome e pelve sem e com contraste', 1),
  ('CT', 'Tomografia Computadorizada para Pesquisa de Litíase Urinária', 'tomografia computadorizada para pesquisa de litíase urinária', 1),
  ('CT', 'Tomografia Computadorizada para Abdome Agudo', 'tomografia computadorizada para abdome agudo', 1),
  ('CT', 'Tomografia Computadorizada de Coluna Cervical', 'coluna cervical', 1),
  ('CT', 'Tomografia Computadorizada de Coluna Torácica', 'coluna torácica', 1),
  ('CT', 'Tomografia Computadorizada de Coluna Lombar', 'coluna lombar', 1),
  ('CT', 'Tomografia Computadorizada de Coluna Lombossacra', 'coluna lombossacra', 1),
  ('CT', 'Tomografia Computadorizada de Ombro Direito', 'ombro direito', 1),
  ('CT', 'Tomografia Computadorizada de Ombro Esquerdo', 'ombro esquerdo', 1),
  ('CT', 'Tomografia Computadorizada de Cotovelo Direito', 'cotovelo direito', 1),
  ('CT', 'Tomografia Computadorizada de Cotovelo Esquerdo', 'cotovelo esquerdo', 1),
  ('CT', 'Tomografia Computadorizada de Punho Direito', 'punho direito', 1),
  ('CT', 'Tomografia Computadorizada de Punho Esquerdo', 'punho esquerdo', 1),
  ('CT', 'Tomografia Computadorizada de Mão Direita', 'mão direita', 1),
  ('CT', 'Tomografia Computadorizada de Mão Esquerda', 'mão esquerda', 1),
  ('CT', 'Tomografia Computadorizada de Quadril Direito', 'quadril direito', 1),
  ('CT', 'Tomografia Computadorizada de Quadril Esquerdo', 'quadril esquerdo', 1),
  ('CT', 'Tomografia Computadorizada de Bacia', 'bacia', 1),
  ('CT', 'Tomografia Computadorizada de Fêmur Direito', 'fêmur direito', 1),
  ('CT', 'Tomografia Computadorizada de Fêmur Esquerdo', 'fêmur esquerdo', 1),
  ('CT', 'Tomografia Computadorizada de Joelho Direito', 'joelho direito', 1),
  ('CT', 'Tomografia Computadorizada de Joelho Esquerdo', 'joelho esquerdo', 1),
  ('CT', 'Tomografia Computadorizada de Perna Direita', 'perna direita', 1),
  ('CT', 'Tomografia Computadorizada de Perna Esquerda', 'perna esquerda', 1),
  ('CT', 'Tomografia Computadorizada de Tornozelo Direito', 'tornozelo direito', 1),
  ('CT', 'Tomografia Computadorizada de Tornozelo Esquerdo', 'tornozelo esquerdo', 1),
  ('CT', 'Tomografia Computadorizada de Pé Direito', 'pé direito', 1),
  ('CT', 'Tomografia Computadorizada de Pé Esquerdo', 'pé esquerdo', 1),
  ('CT', 'Tomografia Computadorizada para Planejamento Odontológico', 'tomografia computadorizada para planejamento odontológico', 1),
  ('CT', 'Tomografia Computadorizada de ATM', 'atm', 1),
  ('CT', 'Tomografia Computadorizada de Articulações Temporomandibulares', 'articulações temporomandibulares', 1),
  ('CT', 'Tomografia Computadorizada Coronária', 'tomografia computadorizada coronária', 1),
  ('CT', 'Escore de Cálcio Coronário', 'escore de cálcio coronário', 1),
  ('CT', 'Angiotomografia Coronária', 'angiotomografia coronária', 1),
  ('CT', 'Enterotomografia', 'enterotomografia', 1),
  ('CT', 'Tomografia Computadorizada de Mastoides', 'mastoides', 1),
  ('CT', 'Tomografia Computadorizada de Face para Trauma', 'face para trauma', 1),
  ('CT', 'Tomografia Computadorizada de Corpo Inteiro para Trauma', 'corpo inteiro para trauma', 1),
  ('MR', 'Ressonância Magnética de Encéfalo sem Contraste', 'encéfalo sem contraste', 1),
  ('MR', 'Ressonância Magnética de Encéfalo com Contraste', 'encéfalo com contraste', 1),
  ('MR', 'Ressonância Magnética de Encéfalo sem e com Contraste', 'encéfalo sem e com contraste', 1),
  ('MR', 'Ressonância Magnética de Hipófise', 'hipófise', 1),
  ('MR', 'Ressonância Magnética de Órbitas', 'órbitas', 1),
  ('MR', 'Ressonância Magnética de Ouvidos Internos / Condutos Auditivos Internos', 'ouvidos internos / condutos auditivos internos', 1),
  ('MR', 'Ressonância Magnética de Seios da Face', 'seios da face', 1),
  ('MR', 'Ressonância Magnética de Face', 'face', 1),
  ('MR', 'Ressonância Magnética de ATM', 'atm', 1),
  ('MR', 'Angiorressonância de Crânio', 'crânio', 1),
  ('MR', 'Angiorressonância de Pescoço', 'pescoço', 1),
  ('MR', 'Angiorressonância de Crânio e Pescoço', 'crânio e pescoço', 1),
  ('MR', 'Ressonância Magnética funcional do Encéfalo', 'ressonância magnética funcional do encéfalo', 1),
  ('MR', 'Ressonância Magnética com Difusão', 'ressonância magnética com difusão', 1),
  ('MR', 'Ressonância Magnética com Perfusão', 'ressonância magnética com perfusão', 1),
  ('MR', 'Ressonância Magnética de Coluna Cervical', 'coluna cervical', 1),
  ('MR', 'Ressonância Magnética de Coluna Torácica', 'coluna torácica', 1),
  ('MR', 'Ressonância Magnética de Coluna Lombar', 'coluna lombar', 1),
  ('MR', 'Ressonância Magnética de Coluna Lombossacra', 'coluna lombossacra', 1),
  ('MR', 'Ressonância Magnética de Coluna Sacrococcígea', 'coluna sacrococcígea', 1),
  ('MR', 'Ressonância Magnética de Plexo Braquial', 'plexo braquial', 1),
  ('MR', 'Ressonância Magnética de Plexo Lombossacro', 'plexo lombossacro', 1),
  ('MR', 'Ressonância Magnética de Tórax', 'tórax', 1),
  ('MR', 'Angiorressonância de Aorta Torácica', 'aorta torácica', 1),
  ('MR', 'Ressonância Magnética Cardíaca', 'ressonância magnética cardíaca', 1),
  ('MR', 'Angiorressonância do Coração e Grandes Vasos', 'angiorressonância do coração e grandes vasos', 1),
  ('MR', 'Ressonância Magnética de Abdome Superior', 'abdome superior', 1),
  ('MR', 'Ressonância Magnética de Fígado', 'fígado', 1),
  ('MR', 'Ressonância Magnética de Pâncreas', 'pâncreas', 1),
  ('MR', 'Ressonância Magnética de Vias Biliares', 'vias biliares', 1),
  ('MR', 'Colangiorressonância', 'colangiorressonância', 1),
  ('MR', 'Ressonância Magnética de Rins', 'rins', 1),
  ('MR', 'Urorressonância', 'urorressonância', 1),
  ('MR', 'Ressonância Magnética de Adrenais', 'adrenais', 1),
  ('MR', 'Angiorressonância de Aorta Abdominal', 'aorta abdominal', 1),
  ('MR', 'Angiorressonância de Artérias Renais', 'artérias renais', 1),
  ('MR', 'Ressonância Magnética de Pelve Feminina', 'pelve feminina', 1),
  ('MR', 'Ressonância Magnética de Pelve Masculina', 'pelve masculina', 1),
  ('MR', 'Ressonância Magnética de Útero', 'útero', 1),
  ('MR', 'Ressonância Magnética de Ovários / Anexos', 'ovários / anexos', 1),
  ('MR', 'Ressonância Magnética de Endometriose', 'endometriose', 1),
  ('MR', 'Ressonância Magnética de Próstata', 'próstata', 1),
  ('MR', 'Ressonância Magnética de Reto', 'reto', 1),
  ('MR', 'Ressonância Magnética de Bexiga', 'bexiga', 1),
  ('MR', 'Ressonância Magnética de Assoalho Pélvico', 'assoalho pélvico', 1),
  ('MR', 'Ressonância Magnética de Mamas sem Contraste', 'mamas sem contraste', 1),
  ('MR', 'Ressonância Magnética de Mamas com Contraste', 'mamas com contraste', 1),
  ('MR', 'Ressonância Magnética de Mamas sem e com Contraste', 'mamas sem e com contraste', 1),
  ('MR', 'Ressonância Magnética de Implantes Mamários', 'implantes mamários', 1),
  ('MR', 'Ressonância Magnética de Ombro Direito', 'ombro direito', 1),
  ('MR', 'Ressonância Magnética de Ombro Esquerdo', 'ombro esquerdo', 1),
  ('MR', 'Ressonância Magnética de Braço Direito', 'braço direito', 1),
  ('MR', 'Ressonância Magnética de Braço Esquerdo', 'braço esquerdo', 1),
  ('MR', 'Ressonância Magnética de Cotovelo Direito', 'cotovelo direito', 1),
  ('MR', 'Ressonância Magnética de Cotovelo Esquerdo', 'cotovelo esquerdo', 1),
  ('MR', 'Ressonância Magnética de Punho Direito', 'punho direito', 1),
  ('MR', 'Ressonância Magnética de Punho Esquerdo', 'punho esquerdo', 1),
  ('MR', 'Ressonância Magnética de Mão Direita', 'mão direita', 1),
  ('MR', 'Ressonância Magnética de Mão Esquerda', 'mão esquerda', 1),
  ('MR', 'Ressonância Magnética de Quadril Direito', 'quadril direito', 1),
  ('MR', 'Ressonância Magnética de Quadril Esquerdo', 'quadril esquerdo', 1),
  ('MR', 'Ressonância Magnética de Coxa Direita', 'coxa direita', 1),
  ('MR', 'Ressonância Magnética de Coxa Esquerda', 'coxa esquerda', 1),
  ('MR', 'Ressonância Magnética de Joelho Direito', 'joelho direito', 1),
  ('MR', 'Ressonância Magnética de Joelho Esquerdo', 'joelho esquerdo', 1),
  ('MR', 'Ressonância Magnética de Perna Direita', 'perna direita', 1),
  ('MR', 'Ressonância Magnética de Perna Esquerda', 'perna esquerda', 1),
  ('MR', 'Ressonância Magnética de Tornozelo Direito', 'tornozelo direito', 1),
  ('MR', 'Ressonância Magnética de Tornozelo Esquerdo', 'tornozelo esquerdo', 1),
  ('MR', 'Ressonância Magnética de Pé Direito', 'pé direito', 1),
  ('MR', 'Ressonância Magnética de Pé Esquerdo', 'pé esquerdo', 1),
  ('MR', 'Ressonância Magnética de Articulação Sacroilíaca', 'articulação sacroilíaca', 1),
  ('MR', 'Ressonância Magnética de Bacia', 'bacia', 1),
  ('MR', 'Ressonância Magnética de Músculo / Partes Moles', 'músculo / partes moles', 1),
  ('MR', 'Ressonância Magnética de Tumoração de Partes Moles', 'tumoração de partes moles', 1),
  ('MR', 'Artro-Ressonância de Ombro Direito', 'ombro direito', 1),
  ('MR', 'Artro-Ressonância de Ombro Esquerdo', 'ombro esquerdo', 1),
  ('MR', 'Artro-Ressonância de Quadril Direito', 'quadril direito', 1),
  ('MR', 'Artro-Ressonância de Quadril Esquerdo', 'quadril esquerdo', 1),
  ('MR', 'Artro-Ressonância de Punho Direito', 'punho direito', 1),
  ('MR', 'Artro-Ressonância de Punho Esquerdo', 'punho esquerdo', 1),
  ('MR', 'Artro-Ressonância de Joelho Direito', 'joelho direito', 1),
  ('MR', 'Artro-Ressonância de Joelho Esquerdo', 'joelho esquerdo', 1),
  ('MR', 'Enterorressonância', 'enterorressonância', 1),
  ('MR', 'Colangiorressonância', 'colangiorressonância', 1),
  ('MR', 'Urorressonância', 'urorressonância', 1),
  ('MR', 'Angiorressonância de Membros Inferiores', 'membros inferiores', 1),
  ('MR', 'Angiorressonância de Membros Superiores', 'membros superiores', 1),
  ('MG', 'Mamografia Bilateral para Rastreamento', 'bilateral para rastreamento', 1),
  ('MG', 'Mamografia Bilateral Diagnóstica', 'bilateral diagnóstica', 1),
  ('MG', 'Mamografia Unilateral Direita', 'unilateral direita', 1),
  ('MG', 'Mamografia Unilateral Esquerda', 'unilateral esquerda', 1),
  ('MG', 'Mamografia com Incidências Complementares', 'com incidências complementares', 1),
  ('MG', 'Mamografia para Controle', 'para controle', 1),
  ('MG', 'Mamografia de Seguimento', 'de seguimento', 1),
  ('MG', 'Mamografia Crânio-Caudal Bilateral', 'crânio-caudal bilateral', 1),
  ('MG', 'Mamografia Médio-Lateral Oblíqua Bilateral', 'médio-lateral oblíqua bilateral', 1),
  ('MG', 'Mamografia Crânio-Caudal Direita', 'crânio-caudal direita', 1),
  ('MG', 'Mamografia Crânio-Caudal Esquerda', 'crânio-caudal esquerda', 1),
  ('MG', 'Mamografia Médio-Lateral Oblíqua Direita', 'médio-lateral oblíqua direita', 1),
  ('MG', 'Mamografia Médio-Lateral Oblíqua Esquerda', 'médio-lateral oblíqua esquerda', 1),
  ('MG', 'Mamografia Perfil Verdadeiro Direita', 'perfil verdadeiro direita', 1),
  ('MG', 'Mamografia Perfil Verdadeiro Esquerda', 'perfil verdadeiro esquerda', 1),
  ('MG', 'Mamografia com Magnificação', 'com magnificação', 1),
  ('MG', 'Mamografia com Compressão Localizada', 'com compressão localizada', 1),
  ('MG', 'Mamografia com Spot Compression', 'com spot compression', 1),
  ('MG', 'Mamografia com Rolagem', 'com rolagem', 1),
  ('MG', 'Mamografia Axilar', 'axilar', 1),
  ('MG', 'Mamografia com Incidências Especiais', 'com incidências especiais', 1),
  ('MG', 'Mamografia Digital com Tomossíntese Bilateral', 'digital com tomossíntese bilateral', 1),
  ('MG', 'Mamografia Digital com Tomossíntese Direita', 'digital com tomossíntese direita', 1),
  ('MG', 'Mamografia Digital com Tomossíntese Esquerda', 'digital com tomossíntese esquerda', 1),
  ('MG', 'Tomossíntese Mamária Bilateral', 'tomossíntese mamária bilateral', 1),
  ('MG', 'Tomossíntese Mamária com Complementação', 'tomossíntese mamária com complementação', 1),
  ('DX', 'Densitometria Óssea de Coluna Lombar', 'coluna lombar', 1),
  ('DX', 'Densitometria Óssea de Fêmur Proximal', 'fêmur proximal', 1),
  ('DX', 'Densitometria Óssea de Fêmur Direito', 'fêmur direito', 1),
  ('DX', 'Densitometria Óssea de Fêmur Esquerdo', 'fêmur esquerdo', 1),
  ('DX', 'Densitometria Óssea de Coluna Lombar e Fêmur', 'coluna lombar e fêmur', 1),
  ('DX', 'Densitometria Óssea de Corpo Inteiro', 'corpo inteiro', 1),
  ('DX', 'Densitometria Óssea de Antebraço', 'antebraço', 1),
  ('DX', 'Densitometria Óssea de Rádio Distal', 'rádio distal', 1),
  ('DX', 'Densitometria Óssea Segmentar', 'densitometria óssea segmentar', 1),
  ('DX', 'Densitometria Óssea com Avaliação de Composição Corporal', 'densitometria óssea com avaliação de composição corporal', 1),
  ('DX', 'Densitometria de Corpo Inteiro para Composição Corporal', 'densitometria de corpo inteiro para composição corporal', 1),
  ('DX', 'Vertebral Fracture Assessment por DXA', 'vertebral fracture assessment por dxa', 1),
  ('DX', 'Avaliação Morfométrica Vertebral por DXA', 'avaliação morfométrica vertebral por dxa', 1);

-- 370 registros inseridos.
